// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzWIrqJ4P3IwE9ceSQxs9aPZhfAvnvgao',
    appId: '1:290656496753:web:9b34e2f935958ca91fbfd0',
    messagingSenderId: '290656496753',
    projectId: 'tager-store',
    authDomain: 'tager-store.firebaseapp.com',
    storageBucket: 'tager-store.firebasestorage.app',
    measurementId: 'G-QXB8MDYQPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG-GfNzHbOadE9pevMG0lWKHCGxmk7XKA',
    appId: '1:290656496753:android:9c98dc48c0f731601fbfd0',
    messagingSenderId: '290656496753',
    projectId: 'tager-store',
    storageBucket: 'tager-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR_rMniqR2hxpiEyn1s5tV4efg4W5omOg',
    appId: '1:290656496753:ios:c59e14e82ff7a13c1fbfd0',
    messagingSenderId: '290656496753',
    projectId: 'tager-store',
    storageBucket: 'tager-store.firebasestorage.app',
    iosBundleId: 'com.sixamtech.sixamMart',
  );
}
