default_platform(:android)

platform :android do
  desc "Lane for Android App Distribution" 
  lane :firebase_distribution do
    # Clean the Flutter project
    # sh "flutter clean"
    
    # Build the APK in release mode
    # sh "fvm flutter build apk --release --no-tree-shake-icons"
    
    # Distribute the APK via Firebase
    firebase_app_distribution(
      app: "1:290656496753:android:9c98dc48c0f731601fbfd0",
      firebase_cli_token: '',
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "Abdoelmorap@gmail.com",
      release_notes: "Tager Store", # Read release notes from a file
    )
  end
end
